### PR TITLE
[MNT] Relax `numpy` bound to `numpy<3.0.0`

### PR DESCRIPTION
**Pull request by XinyuWuu**
Relaxes `numpy` bound to `numpy<3.0.0`.

(updated by @fkiraly - removed the `optuna` bound which has been dealt with in https://github.com/jdb78/pytorch-forecasting/pull/1629)

---

It should work with newer `numpy` and `optuna` version after #1599.

### CODE REVIEW

**Comment by XinyuWuu** [comment]
numpy2 support of torch: https://github.com/pytorch/pytorch/issues/107302#issuecomment-2048405223

macOS x86 builds / test deprecation: https://github.com/pytorch/pytorch/issues/114602

It seems impossible to have numpy2 and torch working in macOS x86.

**Comment by fkiraly** [comment]
Why is this not a problem in the `sktime` runners, where we have `torch` models and also an OS matrix?

**Comment by XinyuWuu** [comment]
> Why is this not a problem in the `sktime` runners, where we have `torch` models and also an OS matrix?

Actully we are having torch 2.2.2 and numpy 1.24 for macos in sktime.

**Comment by fkiraly** [comment]
do you know what causes that? because for sure we have numpy 2 on most jobs (right?)

**Comment by XinyuWuu** [comment]
> do you know what causes that? because for sure we have numpy 2 on most jobs (right?)

pytorch has deprecated macOS x86 after version 2.2.2, but torch 2.2.2 do not suppurt numpy2.

**Comment by fkiraly** [comment]
I see, so we are forced torch <2.2 because we enforce numpy 2, am I understanding correctly?

**Comment by XinyuWuu** [comment]
> I see, so we are forced torch <2.2 because we enforce numpy 2, am I understanding correctly?

We are forced numpy 1 because we are forced torch<=2.2.2. We can not install torch>2.2.2 in macOS x86 because pytorch has deprecated it after 2.2.2. We can not support numpy 2 in macOS x86 because pytorch supports numpy 2 only with torch>=2.3.0 which can not be installed in macOS x86.

**Comment by fkiraly** [comment]
I think the issue is resolved by using `macos-latest`, which is 64 and not 86

**Pull request merged**
