### PR TITLE
[MNT] Remove mutable objects from defaults

### PR DESCRIPTION
**Pull request by eugenio-mercuriali**
### Description

This PR is a fix for #1668. Removes mutable default arguments and replaces them with internal newly initialized mutable defaults.

### Checklist

- [x] Linked issues (if existing)
- [ ] Amended changelog for large changes (and added myself there as contributor)
- [x] Added/modified tests
- [x] Used pre-commit hooks when committing to ensure that code is compliant with hooks. Install hooks with `pre-commit install`.
      To run hooks independent of commit, execute `pre-commit run --all-files`

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Nice!

I think this is great and can be in a single PR.

Some small issues:

* the tests are failing due to type annotations, have a look at the logs
* not a strict requirement, but it might be safer in case of `__init__` to write the resolved argument to a parameter `self._parametername`, to ensure `self.parametername` is always identical with the `__init__` input. This is a "dataclass-like" interface which may be useful later in interfacing sklearn and similar libraries.

**Comment by eugenio-mercuriali** [comment]
> Nice!
> 
> I think this is great and can be in a single PR.
> 
> Some small issues:
> 
> * the tests are failing due to type annotations, have a look at the logs
> * not a strict requirement, but it might be safer in case of `__init__` to write the resolved argument to a parameter `self._parametername`, to ensure `self.parametername` is always identical with the `__init__` input. This is a "dataclass-like" interface which may be useful later in interfacing sklearn and similar libraries.

I see, thanks for the feedback!
Added some changes - how does this look?

**Review by fkiraly — CHANGES_REQUESTED** [review]
Looks great!

Though, for the `__init__`-s, you would *still* do `self.paramname = paramname`, just not change it, e.g.,

```python
self.groups = groups
self._groups = do_sth_with_groups(groups)
```

so the class behaves like a `dataclass` with respect to its init parameters.

There were also a lot of linting failures related to the introduction of stricter requirements in `ruff`, I fixed most of them. The remaining ones seem genuine code issues, could you have ea look?

**Comment by eugenio-mercuriali** [comment]
> Looks great!
> 
> Though, for the `__init__`-s, you would _still_ do `self.paramname = paramname`, just not change it, e.g.,
> 
> ```python
> self.groups = groups
> self._groups = do_sth_with_groups(groups)
> ```
> 
> so the class behaves like a `dataclass` with respect to its init parameters.
> 
> There were also a lot of linting failures related to the introduction of stricter requirements in `ruff`, I fixed most of them. The remaining ones seem genuine code issues, could you have ea look?

Just for me to understand, let's take the `__init__` of _encoders.py_ as an example:
if instead of:

`self._groups = list(groups) if groups is not None else []`

we do:

```
self.groups = groups
self._groups = list(groups) if groups is not None else []
```

then we would have to refactor usages of `self.groups` to `self._groups` in order to use the resolved argument within the class (+ no need to create a _groups_ property) - is this what you suggest?

**Comment by fkiraly** [comment]
> is this what you suggest?

Yes, exactly what I mean.
I confirm your understanding agrees with mine, @eugenio-mercuriali.

The high-level rationale is that the class then behaves, at all times of usage, like a `dataclass` with respect to its init parameters.

**Comment by eugenio-mercuriali** [comment]
> > is this what you suggest?
> 
> Yes, exactly what I mean. I confirm your understanding agrees with mine, @eugenio-mercuriali.
> 
> The high-level rationale is that the class then behaves, at all times of usage, like a `dataclass` with respect to its init parameters.

@fkiraly added changes based on the above. Could you take a look?

**Comment by eugenio-mercuriali** [comment]
@fkiraly are there any adjustments needed or good to merge?

**Pull request merged**
